name: StatsRedirect
version: 1.0
main: org.sunik.statsredirect.StatsRedirect
api-version: '1.16'
commands:
  stats:
    description: 스탯 관련 기능입니다.
    usage: /stats
  statslist:
    description: 명령어 리스트입니다.
    usage: /statslist
  stats reset:
    description: 스텟 초기화입니다.
    usage: /stats reset
  heal:
    description: 모든 디버프 해제 및 회복합니다.
    usage: /heal
  status:
    description: 사용자 프로필을 확인합니다.
    usage: /status
  level:
    description: 레벨을 수정 및 리셋합니다.
    usage: /level